# Generated by Django 4.2.27 on 2026-04-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.croptype')),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Plot name or area code', max_length=200)),
                ('planting_date', models.DateField()),
                ('number_of_plants', models.PositiveIntegerField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Growing', max_length=50)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='crops.variety')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity in kg')),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.plantation')),
            ],
        ),
    ]
