# Generated by Django 4.2.27 on 2026-04-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croptype',
            name='description',
        ),
        migrations.AddField(
            model_name='croptype',
            name='icon',
            field=models.CharField(default='fa-leaf', max_length=50),
        ),
        migrations.AddField(
            model_name='plantation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plantation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantation',
            name='soil_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quality',
            field=models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C')], default='Grade A', max_length=50),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.FloatField(help_text='in kg'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='location',
            field=models.CharField(help_text='Field Name or Section ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='number_of_plants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='status',
            field=models.CharField(choices=[('Growing', 'Growing'), ('Harvesting', 'Harvesting'), ('Dormant', 'Dormant'), ('Problem Detected', 'Problem Detected')], default='Growing', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.variety'),
        ),
    ]
