# Generated by Django 4.2.27 on 2026-04-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name_plural': 'Livestock'},
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='notes',
            new_name='health_notes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-paw', max_length=50),
        ),
        migrations.AddField(
            model_name='livestock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='location',
            field=models.CharField(default='Main Shed', help_text='Pen, Tank, or Shed Number', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.breed'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='identifier',
            field=models.CharField(help_text='Tag ID or Name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('In Quarantine', 'In Quarantine'), ('Sold', 'Sold'), ('Deceased', 'Deceased')], default='Healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='weight',
            field=models.FloatField(blank=True, help_text='in kg', null=True),
        ),
    ]
